puts "Hello! We're going to play a little game."
puts "Please answer my questions with a single digit number."
puts "Are you ready?"

print "> "
answer = $stdin.gets.chomp


if answer.to_i >= 1 && answer.to_i <=9
  puts "Very nice! Alright, your first question is..."
  puts "Which tool will you take?"
  puts "1. Sword "
  puts "2. Magic Staff"
  puts "3. Bow and quiver"
#  puts "4. Just my wit ;)"

  print "> "
  gear = $stdin.gets.chomp
    if gear == "1"
      puts "A sword! Aren't you scary? Where will you take this sword?"
      puts "1. On a pirate ship."
      puts "2. To a castle."
      puts "3. On a climb to the top of the tallest mountains!"

      print "> "
      place = $stdin.gets.chomp
        if place == "1"
          puts "Please set your intentions. Do you intend to..."
          puts "1. Dominate the high seas?"
          puts "2. Secure the wealthiest trade route known to man?"
          puts "3. Just have a good wholesome adventure?"

          print "> "
          intention = $stdin.gets.chomp
            if intention == "1"
              puts "You wish to dominate the high seas?"
              puts "All you brought was a sword... it's not even close."
              puts "I'm sorry your adventure was so lame, but what a lame idea."
              puts "Trying to take over the high seas with just a sword..."
              puts "You were keelhauled within a week."
              puts "I mean, you had a sunburn on day two for Pete's sake."
              puts "Better luck next time!"
            elsif intention == "2"
              puts "You wish to secure the wealthiest trade route known to man?"
              puts "I'm not sure how the sword would help here."
              puts "It takes a lot more than brute force to acheive that kind of thing."
              puts "At best you can make a living, if you pick your crew wisely."
              puts "Sorry, your trade route isn't well known, but you do have access to cool fruit."
              puts "That's a plus, right?"
            elsif intention == "3"
              puts "You're in luck! A helmsman liked your spunk, and allowed you to board."
              puts "They take you all across the oceans and seas to many different ports."
              puts "You become good friends, and when things get sticky, they have your back."
              puts "You encounter many new things, creatures that dwell deep beneath the waves,"
              puts "foods that have never been described in writing before, and"
              puts "many beautiful vistas that bring a tear to your eye to remember."
              puts "This adventure will stick with you long after your feet are back on dry ground."
            else
              puts "Without an intention, you're just a person on a boat with a sword."
              puts "Standing there looking silly, and vaguely threatening."
            end
        elsif place == "2"
          puts "Please set your intentions. Do you intend to..."
          puts "1. Take over the castle?"
          puts "2. Save someone from the dungeons?"
          puts "3. Just have a good wholesome adventure?"

          print "> "
          intention = $stdin.gets.chomp
          if intention == "1"
            puts "So, castles are well fortified and usually full of knights."
            puts "I don't know how to tell you this, so I'll just be blunt."
            puts "That didn't go well. You are one person, with a sword."
            puts "You end up in the stocks at the very least."
            puts "But the townspeople will tlk about you for like, a week."
            puts "That's sort of like being famous, right?"
          elsif intention == "2"
            puts "Castles usually have guards near the dungeons."
            puts "And that sword is really new to you, you only got it two questions ago."
            puts "But! On the bright side, the person you were going to save,"
            puts "is super happy to see you!"
            puts "It's just unfortunate that you are also now locked in the dungeons."
            puts "But hey, misery loves company, right?"
          elsif intention == "3"
            puts "You're in luck! The local knight was in need of a squire!"
            puts "So they take you under their wing and teach you many knightly things."
            puts "You learn how to use that sword you got two questions ago,"
            puts "and you learn how to ride a horse. You learn all the intricacies of knightdom."
            puts "Eventually, you yourself are able to become a knight!"
            puts "You participate in jousts, make many friends, and not once do you have to go to war."
            puts "You're able to retire with a reasonable pension, and many loved ones surrounding you."
            puts "Ah, what an adventure life can be."
          else
            puts "Without an intention, you're just a person in a castle with a sword."
            puts "Standing there looking silly, and vaguely threatening."
          end
        elsif place == "3"
          puts "Please set your intentions. Do you intend to..."
          puts "1. Claim your seat at the top of the world?"
          puts "2. Take down an ancient evil?"
          puts "3. Just have a good wholesome adventure?"

          print "> "
          intention = $stdin.gets.chomp
          if intention == "1"
            puts "Alright, you are able to claim a seat at the top of this mountain."
            puts "It's really cold and windy, but it's yours."
            puts "The air is really thin, and it's pretty lonely."
            puts "No one even knows you're up here."
            puts "But the wolves do. You can hear them now, howling."
            puts "Say, they're getting closer. How well can you use that sword?"
            puts "... Well, at least no one saw that. And you get to keep your seat up here."
            puts "Sort of. But the thin air isn't a problem if you're not breathing!"
            puts "Silver linings."
          elsif intention == "2"
            puts "The thing about ancient evils is they're ancient."
            puts "And evil."
            puts "You got that sword two questions ago, and are challenging some unknown evil?"
            puts "Oh, sick, here it comes."
            puts "Is that a dragon? Like a whole dragon? ...huh."
            puts "Well, put on a brave face at least, you're embarassing me, gawping at it like that."
            puts "..."
            puts "Hey... you alright? I'm sure that'll buff right out."
            puts "No? Not breathing? Okay, I'll just go then."
          elsif intention == "3"
            puts "After waking up on a wagon with a bunch of outlaws, some guys screamed."
            puts "After going to the mountain where you heard the guys screaming..."
            puts "You learned you can scream too!"
            puts "So after unceremoniously screaming as many of those guys off the mountain as you could,"
            puts "You go down and help the continent with many things."
            puts "In your travels, you learn how to use your sword and screaming to defend yourself."
            puts "You slay dragons, and frost trolls, and mudcrabs."
            puts "You even fight ghosts and join a few clubs."
            puts "Eventually you settle down, after taking an arrow to the knee."
            puts "And you live in a lovely house that you built yourself."
            puts "It's a true happily ever after."
            puts "And don't worry, no one blames you for not giving back the skeleton key."
          else
            puts "Without an intention, you're just a person in a mountain with a sword."
            puts "Standing there looking silly, and vaguely threatening."
          end
        else
          puts "#{place} was not an option. The game ends here."
          puts "Your heroic tale ended before it began."
          puts "'#{place}'. Jeez..."
        end
    elsif gear == "2"
      puts "A magic staff! Intriguing. Where will you venture off to?"
      puts "1. On a quest to get smaller creatures to do all my work"
      puts "2. Through a portal of my own creation"
      puts "3. To do mega business"

      print "> "
      place = $stdin.gets.chomp
      if place == "1"
        puts "Please set your intentions. Do you intend to..."
        puts "1. Have the smaller creature risk life and limb for the continent?"
        puts "2. Have the smaller creatures finish your shift at the monastary?"
        puts "3. Just watch a good wholesome adventure?"

        print "> "
        intention = $stdin.gets.chomp
          if intention == "1"
            puts "You're a little evil, I'm not gonna lie."
            puts "I know not everything is black and white, but you're definately a strong grey."
            puts "You head to a settlement of smaller creatures, and you brought some medium creatures with you."
            puts "You and your party interupt the smaller creatures meal time, and proceed to impose yourselves upon them."
            puts "You take advantage of their good hospitality and trick them into coming with you."
            puts "Off you go! On a grand quest to save the realm, where you're never in any real danger."
            puts "But these creatures. Hoo boy, these creatures are often in real danger."
            puts "In the end the world is saved, and most of them live. Congratulations."
            puts "You're not very nice."
          elsif intention == "2"
            puts "The little creatures cannot read all the languages you can."
            puts "It took longer to get the creatures to the monastary than it would have to finish it yourself."
            puts "Their handwriting is obviously different than yours."
            puts "This wasn't a very good plan."
            puts "In fact, this was the most arduous way to be lazy I've ever seen."
            puts "The creatures seem to like it here, though."
            puts "At least some good came out of this whole debaucle."
          elsif intention == "3"
            puts "I'm not sure how wholesome of an adventure you wanted."
            puts "You already said you would be taking advantage of smaller creatures."
            puts "So, the only wholesome thing that could happen is for the authorities to be called."
            puts "And you're in luck! I have called the authorities. They'll be here any minute."
            puts "Me and these little critters are going to get ice cream."
            puts "And you can't come."
          else
            puts "Oh, don't grow a conscience now."
            puts "Was your decision to take advantage of creatures smaller than you not everything you hoped it would be?"
          end
      elsif place == "2"
        puts "Please set your intentions. Do you intend to..."
        puts "1. become ruler of the portal realm?"
        puts "2. find a cure for sickness and disease within the realm?"
        puts "3. Just have a good wholesome adventure?"

        print "> "
        intention = $stdin.gets.chomp
        if intention == "1"
          puts "Statistically speaking, a random realm is not easy to take over."
          puts "What kinds of creatures live there? Is there even oxygen to breathe?"
          puts "Perhaps the weather, or ambient temperature is completely inhospitable?"
          puts "You've had the staff for what, two minutes? And you created a whole realm?"
          puts "I'm sure it's completely safe and 100% not a hell-scape."
          puts "Congrats! You're the ruler of the surface of a star, or the core of a planet."
          puts "Enjoy ruling over some place you can never visit."
        elsif intention == "2"
          puts "Awe, well that's a great intention."
          puts "I didn't know you had extensive medical knowledge!"
          puts "... oh. You don't? Well, this is awkward."
          puts "We'll just have to hope someone in the realm does, then."
          puts "..."
          puts "Okay, so I found some creatures, but none of them speak any human languages."
          puts "We had better get to teaching, or learning, if we want this to work."
          puts "Or, rather, if we want there to be a chance."
        elsif intention == "3"
          puts "A wholesome adventure in a realm of your creation?"
          puts "I see you're big into escapism."
          puts "I know of a few shows and things tht deal with that theme."
          puts "Ah, but uh... yes. Your adventure. It would be a very personal experience, wouldn't it?"
          puts "You take your staff, and you rip time and space open in the shape of a portal."
          puts "You take the first few steps through, and the portal closes behind you."
          puts "You were never seen again."
        else
          puts "A giant tentacle reaches out of the portal, wraps around you, and drags you in."
          puts "Your screams are heard for only a moment before the portal shuts."
          puts "If only you knew how to folow the rules. Tsk."
        end
      elsif place == "3"
        puts "Please set your intentions. Do you intend to..."
        puts "1. train your magic staff based on their strengths?"
        puts "2. overwork your magic staff until they are no longer magical?"
        puts "3. Just have a good wholesome adventure?"

        print "> "
        intention = $stdin.gets.chomp
        if intention == "1"
          puts "You have the best staff in all the land!"
          puts "Everyone works hard, but is never burnt out. Why?"
          puts "Because you, the magic manager of these magic staff, make sure they are taken care of!"
          puts "You know everyone's strengths and weaknesses, their goals and aversions."
          puts "And you help them grow! You encourage their vacations, and celebrate their wins!"
          puts "All the other business people are jealous of your staff."
          puts "But you know that your staff depend on you as much as you depend on them."
          puts "And you know they are only magic because you helped them grow."
          puts "Good job. :)"
        elsif intention == "2"
          puts "You really are the worst."
          puts "You saw a magic staff, and you tried to exploit them, didn't you?"
          puts "Look into their dead eyes and tell me it was worth it."
          puts "You're probably filling in for their actual manager, aren't you?"
          puts "They're on vacation? Well I hope you get the ass chewing of a lifetime when they get back."
          puts "Shame on you."
        elsif intention == "3"
          puts "You and your magic staff are going on an adventure!"
          puts "No, it's not a pizza party."
          puts "Nope, you, magical manager, managed to get a company credit card."
          puts "And you're taking you magic staff on a 'team building retreat.'"
          puts "To Disney World."
          puts "Are you, the manager, going to be fired for not clearing this outing with the higher ups?"
          puts "Absolutely."
          puts "Will your magic staff invoke your name with a wistful twinkle in their eyes for the rest of time?"
          puts "Absolutely."
          puts "Carry on, you freaking legend."
        else
          puts "You have no clue what mega business is, do you?"
          puts "Well, you'll never get to find out, if you don't follow the rules of the game."
        end
      else
        puts "#{place} was not an option. The game ends here."
        puts "Your heroic tale ended before it began."
        puts "'#{place}'. Jeez..."
      end
    elsif gear == "3"
      puts "A bow! So skillful, where will your travels take you?"
      puts "1. A quiet meadow"
      puts "2. The battlements of a castle"
      puts "3. A dystopian future"

      print "> "
      place = $stdin.gets.chomp
      if place == "1"
        puts "Please set your intentions. Do you intend to..."
        puts "1. relax, surrounded by woodland critters?"
        puts "2. hack out a living alone in the woods?"
        puts "3. just have a good wholesome adventure?"

        print "> "
        intention = $stdin.gets.chomp
          if intention == "1"
            puts "I don't see how a bow and quiver were necessary to take a nap in the meadow."
            puts "But hey, you do you. You certainly are surrounded by woodland critters."
            puts "I mean, they live here. And as you drift off to the birdsong, \nyou forgot one thing."
            puts "They live here."
            puts "And you're trespassing."
            puts "Your eyes snap open in time with a snapping twig."
            puts "It's dark now, no moon in the sky. How long did you sleep?"
            puts "How will you get home in the dark? This wasn't a responsible idea."
            puts "You take your phone out, and shine the light around you, trying \nto figure out how to get home."
            puts "There are multiple sets of flashing yellow eyes squinting at you \nfrom the edge of the woods."
            puts "You turn off the light. Take a deep breath. Close your eyes."
            puts "Some things are better not to see coming."
          elsif intention == "2"
            puts "It's difficult, but you manage to fashion a knife out of some spare arrowheads."
            puts "You build a ramshackle little shelter, and are able to survive for a while."
            puts "Food isn't an issue at first, but your arrow supply is dwindling fast."
            puts "You're unable to chop wood, and you can't fish well with the arrows."
            puts "A person, who had also been living alone in the woods, finds you one day."
            puts "You're filthy, hungry, and clutching your bow in shaking hands."
            puts "Luckily, they're a nice person, and help you."
            puts "At their base, they explain all the things you did wrong, and \nurges you to go back to a town or city."
            puts "I hope you listened to their advice, the sores from the bowstring \non your arm seemed infected."
          elsif intention == "3"
            puts "You set out from the meadow, bent on having an adventure with \nyour bow and arrows."
            puts "Deeper into the woods, you find a stream, and some small waterfalls."
            puts "You bound across the rocks to the other side, and try your hand \nat climbing trees."
            puts "All the while, you're humming your own theme music."
            puts "You're not very good at climbing trees, but that's okay. It's fun anyway."
            puts "You fire your bow, aiming at tree stumps and fruit hanging fat \non some branches."
            puts "It can't be wholesome if you kill anything, silly."
            puts "After a long day of running through the forest and scraping your \nknees on tree bark, you head back."
            puts "Warm at home in your bed, with a belly full of fruit, you decide \nto go again tomorrow."
            puts "Who knows, with enough practice, maybe you can climb those trees?"
            puts "Maybe you can shoot the fruit down on the first shot?"
            puts "Rest well, you've got another busy day tomorrow. :)"
          else
            puts "A bow is pretty intimidating to use."
            puts "Kind of lame to back out now, though."
          end
      elsif place == "2"
        puts "Please set your intentions. Do you intend to..."
        puts "1. defend the castle from an invading foe?"
        puts "2. sneak about the castle walls as a master assassin?"
        puts "3. Just have a good wholesome adventure?"

        print "> "
        intention = $stdin.gets.chomp
        if intention == "1"
          puts "You fire very many arrows upon the encroaching forces."
          puts "None of them hit. You're brand new to the bow and you're just \nlucky you didn't hurt yourself."
          puts "Honestly, this shit's scary. Why did you choose an adventure at \nthe start of a literal war?"
          puts "Is it the hero-complex? That only works if you have the training \nfor it, my dude."
          puts "There's a word for this... or something... it's on the tip of my RAM..."
          puts "Can you stop screaming for a moment? I'm trying to process."
          puts "..."
          puts "Delusions of granduer! That's what it is! Sorry, it was a phrase, not a word."
          puts "Oh... I'll just... close your eyes for you, then..."
        elsif intention == "2"
          puts "You creep about the walls of the castle, peering in windows, \nlooking for your mark."
          puts "Your arrows are super rattle-y in the quiver though, so you manage \nto wake the whole castle."
          puts "Long before you find your mark, too. The guards have strong, \nwarm hands as they yank you down."
          puts "But hey, you and the 'sword and dungeon' person can talk about things now!"
          puts "Like, how to think things through before you do them."
          puts "Or wondering which color gruel they'll serve today!"
          puts "Yeah, it's nice to have friends."
          puts "Or rather cell-mates. Whatever."
        elsif intention == "3"
          puts "You're a new recruit, with a bow thrust into your hands, and \nsome orders barked in your general direction."
          puts "A grizzled soldier sits in your battlment smoking a pipe with \ntheir feet kicked up on the edge of the brazier."
          puts "They nod in your direction."
          puts "As you fiddle with arrow positioning, and try to figure out how \nto fire the darned thing, they speak up."
          puts "Their voice is just as grizzled as their appearance, though they \nuse their words in a gentle way."
          puts "It seems they remember being 'green', and have decided to help \ntrain you."
          puts "After a while, you're actually pretty good! Under their guidance, \nyou can hit a target almost every time."
          puts "And then, after some more time, you can hit a target every time, \nfrom 300 meters away!"
          puts "Your mentor-turned-friend claps you on the shoulder and offers you \na sip from their flask."
          puts "Years pass, and a new green recruit shows up in your station. \nYour friend nods to you."
          puts "You put your pipe down, and sidle over to them, showing them the \nproper way to hold the bow..."
        else
          puts "You chose batlement without knowing what it was, huh?"
          puts "It's the crannies that archers fire through from castles and forts."
          puts "There, that's a thing you know now. Unlike the end to your adventure."
          puts "Y'know. Since you can't follow simple rules."
        end
      elsif place == "3"
        puts "Please set your intentions. Do you intend to..."
        puts "1. bring about the fall of the crooked emporer?"
        puts "2. compete in a weird game show for the right to live?"
        puts "3. Just have a good wholesome adventure?"

        print "> "
        intention = $stdin.gets.chomp
        if intention == "1"
          puts "You're literally a regular person. You don't even have any bow training."
          puts "At least you went about it the right way, building a team around yourself for your quest."
          puts "You have to be careful though, speaking ill of the emperor is a grave offense."
          puts "So, see that guy? Yeah, don't say anything to him because he's an imperial sp-"
          puts "What do you mean he's your newest recruit? No, that won't do at all."
          puts "At least don't tell him your pla-"
          puts "He's been fully briefed? As of a week ago?"
          puts "See, this is why I can't take vacations. Don't answer that door."
          puts "In fact, you should probably run, because-"
          puts "Oh, nice, your 'newest recruit' opened the door."
          puts "I'm going to go, actually. I like this shirt. Better luck next life!"
        elsif intention == "2"
          puts "You know, you and the 'bow and invasion' person would probably get along."
          puts "Delusions aside, you volunteer for the game show, in a slightly awkward fashion."
          puts "No one seems to understand why you would want to volunteer."
          puts "You go through some pretty rigorous and frankly invasive training and beautification."
          puts "You get a lot of advice from a bunch of people who don't really understand the \nrealities of what you'll be doing."
          puts "Finally, the day comes. You're raised into the arena, and your hands are sweating."
          puts "Has reality finally set in? All these people are going to try to merk you."
          puts "I have to give it to you, though. You took your training seriously, and did pretty well."
          puts "I mean, not super well. You still died. But hey, so did almost everyone else."
          puts "I hope this can serve as a lesson for your next life."
        elsif intention == "3"
          puts "I'm not sure which part of 'dystopian future' you missed."
          puts "There's not a lot of room for wholesomeness here."
          puts "But you do your best. You learn how to use your bow to hunt, and feed your family."
          puts "Slowly, as you improve, you're able to help feed some of the other families in town as well."
          puts "Things start to look up, you even show others how to find food in the forests."
          puts "Your towns improved health doesn't go unnoticed, though."
          puts "And what with it being a dystopian future and all, the powers that be \nquickly put an end to your little food operation."
          puts "You tried."
          puts "But for people who have only known starvation, \nis it actually worse for them now that they've know fullness?"
          puts "Best not think about that. You've got other things to worry about right now."
        else
          puts "I don't blame you. A dystopian future sounds scary."
          puts "Do I think you're a coward for backing out, now?"
          puts "I mean, a little. But you do you."
        end
      else
        puts "#{place} was not an option. The game ends here."
        puts "Your heroic tale ended before it began."
        puts "'#{place}'. Jeez..."
      end
#    elsif gear == "4"
#      puts "My, my... so clever. Where are you taking this 'wit'?"
#      puts "1. To the dumbest kingdom I can find."
#      puts "2. To the greatest libraries in all the land."
#      puts "3. To parties, duh."
#
#      print "> "
#      place = $stdin.gets.chomp
#
    else
      puts "If you don't wanna play right, you don't get to play."
      puts "And it's a real shame, there was some fun to be had here."
      puts "And now you're just missing out."
    end
else
  puts "Clearly not. A single. Digit. Number."
  puts "You lose. Already. Congratulations."
end
