animals = ['bear', 'ruby', 'peacock', 'kangaroo', 'whale', 'platypus']

ruby = animals[1]
peacock = animals[2]
bear = animals[0]
kangaroo = animals[3]
whale = animals[4]
peacock = animals[2]
playpus = animals[5]
whale = animals[4]

animals = ['bear', 'tiger', 'penguin', 'zebra']
bear = animals[0]

colors = ['red', 'blue', 'yellow', 'green', 'purple', 'orange']
blue = colors[1]
green = colors[3]
purple = colors[4]
red = colors[0]
orange = colors[5]
